services:
  app:
    container_name: pets-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - pets-api

  nginx:
    container_name: pets-api-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - pets-api
    depends_on:
      - app

  db:
    container_name: pets-db
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    env_file:
      - .env
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pets-api

networks:
  pets-api:
    driver: bridge